---
driver:
  name: docker
  privileged: true

platforms:
  - name: ubuntu-12.04
    run_list: recipe[apt]
    driver_config:
      image: ubuntu-upstart:12.04
  - name: ubuntu-14.04
    run_list: recipe[apt]
    driver_config:
      image: ubuntu-upstart:14.04
  - name: centos-7
    driver_config:
    # https://registry.hub.docker.com/u/milcom/centos7-systemd/dockerfile/
    image: milcom/centos7-systemd
    privileged: true