---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: centos-6.7
  - name: centos-7.2
  - name: fedora-22
  - name: fedora-23

suites:
  - name: default
    run_list:
      - recipe[solr_6::install]
      - recipe[solr_6::deploy]
    attributes:
      solr:
        deploy_url: 'https://s3.amazonaws.com/assets.datacaffeine.net/mirror/test_core.tar.gz'
