---
driver:
  name: docker
  privileged: true

platforms:
  - name: ubuntu-12.04
    run_list: recipe[apt]
    driver_config:
      image: ubuntu-upstart:12.04
  - name: ubuntu-14.04
    run_list: recipe[apt]
    driver_config:
      image: ubuntu-upstart:14.04
  - name: amazonlinux-2017.03
    driver_config:
      platform: centos
  # - name: centos-7
  #   driver_config:
  #     image: milcom/centos7-systemd
  #     privileged: true
  # - name: fedora
  #   driver_config:
  #     image: fedora/systemd-systemd
  #     privileged: true