---
driver:
  name: docker
  privileged: true

platforms:
  - name: ubuntu-12.04
    run_list: recipe[apt]
    driver_config:
      image: ubuntu-upstart:12.04
  - name: ubuntu-14.04
    run_list: recipe[apt]
    driver_config:
      image: ubuntu-upstart:14.04