---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: centos-6.7
  - name: centos-7.2
  - name: debian-7.10
  - name: debian-8.4
  - name: fedora-22
  - name: fedora-23

suites:
  - name: default
    run_list:
      - recipe[solr_6::install]
    attributes:
