---
driver:
  name: docker
  privileged: true

platforms:
  - name: ubuntu-12.04
    run_list: recipe[apt]
    driver_config:
      image: ubuntu-upstart:12.04
  - name: ubuntu-14.04
    run_list: recipe[apt]
    driver_config:
      image: ubuntu-upstart:14.04
  - name: centos-6.7
    run_list: recipe[apt]
  - name: centos-7.2
    run_list: recipe[apt]
  - name: fedora-22
    run_list: recipe[apt]
  - name: fedora-23
    run_list: recipe[apt]