---
PreCommit:
  ALL:
    on_warn: fail    # Treat all warnings as failures
  BrokenSymlinks:
    enabled: true
  BundleAudit:
    enabled: true
    description: 'Run bundle-audit'
    required_executable: './bin/bundle-audit'
    flags: ['check', '--update']
    install_command: 'gem install bundler-audit'
    include:
      - 'Gemfile'
      - 'Gemfile.lock'
  BundleCheck:
    enabled: true
  CaseConflicts:
    enabled: true
  Foodcritic:
    enabled: true
    description: 'Run foodcritic'
    require_files: false
    required_executable: './bin/foodcritic'
    install_command: 'gem install foodcritic'
    flags: ['-f', 'any', '-B', '.']
  HardTabs:
    enabled: true
  JsonSyntax:
    enabled: true
  LocalPathsInGemfile:
    enabled: true
  MergeConflicts:
    enabled: true
  RuboCop:
    enabled: true
    flags: ['--format=emacs', '--force-exclusion', '--display-cop-names']
  ShellCheck:
    enabled: true
  TrailingWhitespace:
    enabled: true
  TravisLint:
    enabled: true
  XmlLint:
    enabled: true
  XmlSyntax:
    enabled: true
  YamlSyntax:
    enabled: true
CommitMsg:
  ALL:
    on_warn: fail
  CapitalizedSubject:
    enabled: false