rvm:
- 2.2

sudo: required
services: docker

env:
  matrix:
    - INSTANCE=default-ubuntu-1204
    - INSTANCE=default-ubuntu-1404
    - INSTANCE=default-fedora
    - INSTANCE=default-amazonlinux-201703
    # - INSTANCE=default-centos-7
    # - INSTANCE=default-centos-67
    # - INSTANCE=default-centos-72
    # - INSTANCE=default-fedora-22
    # - INSTANCE=default-fedora-23

before_install: curl -L https://www.getchef.com/chef/install.sh | sudo bash -s -- -P chefdk -v 0.18.30

install:
  # - if [ $INSTANCE = default-centos-72 ]; then sudo yum -y install initscripts && yum clean all; fi
  - chef exec bundle install

before_script: sudo iptables -L DOCKER || sudo iptables -N DOCKER

script:
# Run test-kitchen with docker driver, for example:
- KITCHEN_LOCAL_YAML=.kitchen.docker.yml chef exec bundle exec kitchen verify ${INSTANCE}
